apiVersion: v1
kind: Namespace
metadata:
  name: minecraft-bedrock-public-server
  annotations:
    field.cattle.io/description: Minecraft java edition server
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-config
  namespace: minecraft-bedrock-public-server
data:
  EULA: "true"
  GAMEMODE: "creative"  # creative/survival/adventure/spectator
  PVP: "false"
  ONLINE_MODE: "false" # disable minecraft server authentication
  SERVER_NAME: "RashtMC"
  DIFFICULTY: "normal"
  ALLOW_FLIGHT: "true"
  ALLOW_CHEATS: "true"
  MAX_PLAYERS: "50"
  OPS: 2533274999471459,2535457030329894
  # MEMBERS: ""
  # VISITORS: ""
  DEFAULT_PLAYER_PERMISSION_LEVEL: "visitor"  # creative/survival/adventure/spectator
  SNOOPER_ENABLED: "false" # Disables minecraft official server feedback
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-bedrock-public-server-data-vol02
  namespace: minecraft-bedrock-public-server
  labels:
    type: local
    usage: game
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: minecraft-bedrock-public-server-data
  hostPath:
    path: /home/rancher/kubernetes/game/minecraft/public-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-bedrock-public-server-public-claim
  namespace: minecraft-bedrock-public-server
spec:
  resources:
    requests:
      storage: 15Gi
  storageClassName: minecraft-bedrock-public-server-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock-public-server
  namespace: minecraft-bedrock-public-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-bedrock-public-server
  template:
    metadata:
      labels:
        app: minecraft-bedrock-public-server
    spec:
      containers:
        - name: minecraft-public
          # image: ghcr.io/rasulalizadeh/minecraft-bedrock-public-server/minecraft-bedrock-public-server:java8-multiarch
          image: ghcr.io/rasulalizadeh/minecraft-server/minecraft-bedrock-server:1.0.0
          resources: 
            limits:
              memory: 1500Mi
          ports:
            - containerPort: 19132
              name: http
              protocol: UDP
              hostPort: 1401
          envFrom:
            - configMapRef:
                name: minecraft-config
          volumeMounts:
            - mountPath: /data
              name: minecraft-bedrock-public-server-public-claim
      volumes:
        - name: minecraft-bedrock-public-server-public-claim
          persistentVolumeClaim:
            claimName: minecraft-bedrock-public-server-public-claim